name: Audit

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean install dependencies
        run: npm ci --legacy-peer-deps #TODO: remove this flag once we get rid of tslint

      - name: Audit signatures
        run: npm audit signatures
