name: build-test-publish

on: [push]

jobs:
  build-test-publish:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Publish
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
